language: node_js

node_js:
  - node

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y rpm
  - npm i -g npm@latest
  - npm install gulp -g

script:
  - npm install
  - gulp release

cache:
  directories:
  - node_modules
